language: java
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
        - bundle install
        - gem install chromium
        - wget http://chromedriver.storage.googleapis.com/2.7/chromedriver_linux64.zip
        - unzip chromedriver_linux64.zip
        - sudo apt-get install libnss3
        - sudo apt-get --only-upgrade install google-chrome-stable
        - sudo cp chromedriver /usr/local/bin/.
        - sudo chmod +x /usr/local/bin/chromedriver
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3
script: mvn test